color0 #46464d
color1 #ffb4ab
color2 #c2c5e0
color3 #c6c5d2
color4 #debdd2
color5 #c2c5e0
color6 #c6c5d2
color7 #e5e1e4
color8 #919097
color9 #ffb4ab
color10 #c2c5e0
color11 #c6c5d2
color12 #debdd2
color13 #c2c5e0
color14 #c6c5d2
color15 #e5e1e4

cursor                #e5e1e4
cursor_text_color     #131315
background            #131315
foreground            #e5e1e4
selection_foreground  #c7c5cd
selection_background  #46464d
active_border_color   #c2c5e0
inactive_border_color #46464d
url_color             #c2c5e0

active_tab_foreground   #2b2f45
active_tab_background   #c2c5e0
inactive_tab_foreground #c7c5cd
inactive_tab_background #46464d
cursor_trail_color      #c7c5cd
