scrollback_lines -1
scrollback_indicator_opacity 0.0
allow_remote_control yes
background_opacity 0.2
cursor_trail 3
cusor_trail_decay 0.1 0.4
confirm_os_windows_close 0
shell_integration enabled


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME