[audio]
enable_overdrive = true

[backdrop]
blur_intensity = 0.04999999888241291

[bar.default]
border_width = 0.5
capsule = true
capsule_opacity = 0.74999998323619366
center = []
color = "primary"
contact_shadow = true
end = [
    "spacer_7",
    "clipboard",
    "battery",
    "cpu",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "spacer_3",
    "tray",
    "spacer_4",
    "notifications",
    "date",
    "clock"
]
font_weight = 300
margin_edge = 4
margin_ends = 12
padding = 8
start = [ "control-center", "wallpaper", "workspaces", "spacer_10", "bongocat", "active_window", "audio_visualizer" ]
thickness = 20
widget_spacing = 4

[control_center]
hidden_tabs = [ "media" ]

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
active_opacity = 0.84999998100101948
active_scale = 0.80000001192092896
auto_hide = true
background_opacity = 0.29999999329447746
cross_axis_padding = 16
icon_size = 48
inactive_opacity = 0.84999998100101948
inactive_scale = 0.85000001266598701
item_spacing = 12
launcher_icon = "bread-filled"
launcher_position = "none"
magnification_scale = 1.2000000029802322
main_axis_padding = 32
margin_edge = 4
margin_ends = 0
pinned = [ "org.gnome.Nautilus", "helium", "kitty" ]
radius = 0
radius_bottom_left = 80
radius_bottom_right = 80
radius_top_left = 80
radius_top_right = 80
reserve_space = false

[location]
auto_locate = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1321.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[nightlight]
enabled = false

[notification]
offset_x = 24
offset_y = 24

[osd]
offset_y = 64
position = "bottom_center"

    [osd.kinds]
    media = true

[shell]
app_icon_color = "primary"
app_icon_colorize = true
corner_radius_scale = 2.0
lang = "en"
polkit_agent = true

    [shell.panel]
    open_near_click_clipboard = false
    open_near_click_control_center = true
    open_near_click_wallpaper = true
    polkit_placement = "attached"
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true
    size = 16

    [shell.shadow]
    alpha = 0.54999998770654202

[theme]
builtin = "Ayu"
community_palette = "Espresso Cream"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "alacritty", "gtk3", "gtk4", "kcolorscheme", "qt", "kitty" ]
    community_ids = [ "vscode", "zed", "discord", "steam", "yazi", "zathura" ]

[wallpaper]
directory = "/home/chri/Pictures"

    [wallpaper.default]
    path = "/home/chri/Pictures/wp12654734-catalina-4k-wallpapers.jpg"

    [wallpaper.last]
    path = "/home/chri/Pictures/wp12654734-catalina-4k-wallpapers.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/chri/Pictures/wp12654734-catalina-4k-wallpapers.jpg"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/chri/Pictures/gtaIV/20260709_22h53m55s_grim.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/chri/Pictures/wp12654734-catalina-4k-wallpapers.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/chri/Pictures/walls/storm.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

[weather]
enabled = false

[widget.active_window]
max_length = 504
show_empty_label = true
title_scroll = "none"

[widget.audio_visualizer]
mirrored = false

[widget.media]
max_length = 300

[widget.network_rx]
network_speed_compact = true

[widget.spacer_10]
type = "spacer"

[widget.spacer_9]
type = "spacer"

[widget.workspaces]
display = "id"
minimal = false